### ISSUE TITLE
Q: Project structure, browser support and ecosystem

### ISSUE THREAD

**Issue by cyalide** [codedust/firefox-sparpreis-helper#2]
Your project seems really interesting and useful to me. To be able to contribute in a beneficial way, I want to point out some general questions about your preferences regarding the future development of the project.

**Do you want to create a more hierarchical project structure?**
If the project grows in size, it can make sense to structure the contents using a classic, hierarchical structure many modern addons use. I could imagine something like this:
```
- manifest.json
- Makefile
- LICENSE
- icons/
  - logo_48px.png
  - logo_96px.png
- js/
  - background.js
  - content-script.js
- css/
  - ps.bahn.de.css
- scripts/
- .gitignore
```

**Do you intend to support other browsers too?**
The extension itself doesn't seem to use any Firefox-specific features, and therefore it should be pretty easy to sustain compability with the Chrome Extension API.

**Do you want to use an ecosystem?**
Currently, the extension is pretty self-sufficient and doesn't rely on external ecosystems like npm.
However, to be able to support multiple platforms and package extensions without reliance on the respective browsers, it's necessary to choose an ecosystem, or you'll stumble into one anyway.
Two options worth considering:
- **Using the Makefile and rely on shell scripts**
This makes the project more platform-dependent, but you don't have to rely on an external registry (like npm).
- **Using the npm ecosystem**
This would allow the usage of cross-platform modules for packaging and many other things that might come in handy in the future, but users would need to have npm installed and you rely on a centralized registry. You could also use a build system like Gulp together with npm, but this would add another pretty big dependency to the project.

Packaging the extensions could be done either by using shell scripts or node modules.

_Using shell scripts:_
XPI-Extensions (for Firefox) can be packaged using zip and CRX-Extensions (for Chrome) can be 'compiled' using [this](https://github.com/darkfe/crxmake) old hex-based bash script.

_Using node modules:_
XPI-Extensions can be packaged using the [firefox-xpi](https://github.com/avast/firefox-xpi) module and CRX-Extensions can be packaged using the [crx](https://github.com/oncletom/crx/) module.

**Comment by codedust** [comment]
Thanks for your ideas. Sorry for the late reply, but I'll try to give some answers for all of your questions. :)

> Do you want to create a more hierarchical project structure?

I didn't had the need for this till now but I'd be open for this. :+1:

> Do you intend to support other browsers too?

I don't use Google Chrome for myself and have no plans to support it in the future (since I don't use it myself and would not recommend Chrome for various reasons to other people). But if someone would like to build support for Google Chrome and would like to maintain Chrome support, I wouldn't stand in his/her way.

> Do you want to use an ecosystem?

No. I don't think the benefits of using an ecosystem such as npm for such a small project are not worth the additional overhead that comes with this. This extension currently doen't even use any external library. I don't think we have any need for this at the moment. The current makefile is just fine imho.

Anyway, thanks for your input! If you have any ideas for possible improvements of the project, feel free to open a feature request issue. :)
